:construction: Fixing pipe error

diff --git a/buildspec-deploy.yml b/buildspec-deploy.yml
--- a/buildspec-deploy.yml
+++ b/buildspec-deploy.yml
@@ -23,8 +23,21 @@ phases:
       - ls -l
   post_build:
     commands:
+      - MAX_RETRIES=3
+      - RETRY_COUNT=0
       - echo $FUNCTION_NAME
       - cd ./$FUNCTION_NAME/dist
       - ls -l
-      - echo Deploying Lambda function to AWS...
-      - aws lambda update-function-configuration --function-name $FUNCTION_NAME --handler src/index-hello-world.handler && aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$FUNCTION_NAME.zip --region us-east-1
+      - echo Updating Lambda function configuration to AWS...
+      - aws lambda update-function-configuration --function-name $FUNCTION_NAME --handler src/index-hello-world.handler 
+      - while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+          aws lambda get-function-configuration --function-name $FUNCTION_NAME
+          if [ $? -eq 0 ]; then
+            echo Deploying Lambda function to AWS...
+            aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$FUNCTION_NAME.zip --region us-east-1
+            break
+          else
+            echo "Update function configuration failed. Retrying..."
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+          fi
+        done
